theme: jekyll-theme-minimal
title: ThaiHealthNewsVerify
description: Development of an Automated Health News Verification Response System in Thai Using Large Language Models and Retrieval-Augmented Generation
